apiVersion: apps/v1
kind: Deployment
metadata:
  name: communities
spec:
  selector:
    matchLabels:
      app: communities
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 5
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: communities
    spec:
      volumes:
      containers:
      - name: communities
        image: "{{ .Values.image }}:{{ .Values.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 0m
        volumeMounts:
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: communities-config
